ci test 5

diff --git a/.github/workflows/forge-test.yml b/.github/workflows/forge-test.yml
--- a/.github/workflows/forge-test.yml
+++ b/.github/workflows/forge-test.yml
@@ -5,11 +5,7 @@ on:
   workflow_call:
     inputs:
       cache-path:
-        default: |
-          cache
-          node_modules
-          out
-          out-optimized
+        default: "cache node_modules out out-optimized"
         required: false
         type: "string"
 
@@ -81,7 +77,7 @@ jobs:
         uses: actions/cache@v3
         with:
           path: foundry
-          key: ${{ runner.os }}-foundry-${{ hashFiles('**/foundry/.gitmodules') }}
+          key: ${{ runner.os }}-foundry-${{ hashFiles('foundry/**') }}
           restore-keys: |
             ${{ runner.os }}-foundry-
 
@@ -90,7 +86,7 @@ jobs:
         uses: actions/cache@v3
         with:
           path: $HOME/.config/.foundry/bin
-          key: ${{ runner.os }}-forge-${{ hashFiles('foundry/Cargo.toml') }}
+          key: ${{ runner.os }}-forge-${{ hashFiles('foundry/**') }}
           restore-keys: |
             ${{ runner.os }}-forge-
 
@@ -113,6 +109,13 @@ jobs:
       - name: Show Forge version
         run: |
           forge --version
+
+      - name: Debug cache path
+        run: |
+          for path in ${{ inputs.cache-path }}; do
+            echo "Listing $path"
+            ls -la "$path" || echo "$path not found"
+          done
 
       - name: "Restore the cached build"
         uses: "itsshantanu/gha-utils/.github/actions/evm-cache@main"
