test 3

diff --git a/.github/workflows/forge-test.yml b/.github/workflows/forge-test.yml
--- a/.github/workflows/forge-test.yml
+++ b/.github/workflows/forge-test.yml
@@ -115,12 +115,20 @@ jobs:
           forge --version
 
       - name: Debug cache path
-        run: ls -la ${{ inputs.cache-path }}
+        run: |
+          for path in ${{ inputs.cache-path }}; do
+            echo "Listing $path"
+            ls -la "$path" || echo "$path not found"
+          done
 
       - name: "Restore the cached build"
         uses: "onlyonejmjq/gha-utils/.github/actions/evm-cache@main"
         with:
-          cache-path: ${{ inputs.cache-path }}
+          path: |
+            cache
+            node_modules
+            out
+            out-optimized
           fail-on-cache-miss: true
 
       - name: "Generate fuzz seed that changes weekly to avoid burning through RPC allowance"
